// export const RouteBack = "http://127.0.0.1:8000";
export const RouteBack = "https://apiclubsincelejo.prismau.com.co";

export const PublicRoutes = {
    LOGIN: "/",
    RECUPERAR: "/reset-user",
    VALIDAR: "/validate-code",
    RESET: "/change-password",
};

export const PrivateRoutes = {
    DASHBOARD: "/dashboard",
    BUSCAR_USER: "/busqueda-usuarios",
    ADMINISTRADORES: "/administradores",
    ASOCIADOS: "/asociados",
    ADHERENTES: "/adherentes",
    EMPLEADOS: "/empleados",
    ESPACIOS: "/espacios",
    ROLES: "/roles",
    HOBBIES: "/hobbies",
    FAMILIARES: "/familiares",
    FAMILIARESASOCIADO: "/familiares-asociado",
    FAMILIARESADHERENTE: "/familiares-adherente",
    PERFIL: "/perfil",
    INVITADOS: "/invitados",
    INVITACIONES: "/invitaciones",
    CARGOS: "/cargos",
    ACCESOS: "/accesos",
    ESTADOS: "/estados",
    NOTICIAS: "/noticias",
    PAGE403: "/403",
    CONTRATOS: "/contratos",
    SOLICITUDES: "/solicitudes",
    RESERVAS: "/reservas",
    ENCUESTAS: "/encuestas",
    ENCUESTA: "/encuesta",
    DISPONIBILIDAD_ESPACIO: "/disponibilidades-espacios",
    PREGUNTAS: "/preguntas",
    RESPUESTAS: "/respuestas",
    RESPUESTAS_ENCUESTA: "/respuestas-encuesta",
    PAGOS: "/pagos",
    RUBROS: "/rubros",
    SOCIOS: "/socios",
    PROGRAMACION_PAGOS: "/programacion-pagos",
    PAGOS_SOCIOS: "/pagos-mensualidades",
    HISTORIAL_PAGOS: "/historial-pagos",
    PAGAR: "/pagar",
    PAGOS_CUOTAS_BAILE: "/pagos-cuotas-baile",
    HISTORIAL_PAGOS_CUOTAS: "/historial-pagos-cuotas"
};

export const EndPoints = {
    ACCESOS: "https://apiclubsincelejo.prismau.com.co/api/entradas",
    ADHERENTES: 'https://apiclubsincelejo.prismau.com.co/api/adherentes',
    ADMINS: 'https://apiclubsincelejo.prismau.com.co/api/admin',
    ASOCIADOS: 'https://apiclubsincelejo.prismau.com.co/api/asociados',
    EMPLEADOS: 'https://apiclubsincelejo.prismau.com.co/api/empleados',
    ESPACIOS: 'https://apiclubsincelejo.prismau.com.co/api/espacios',
    ESTADOS: 'https://apiclubsincelejo.prismau.com.co/api/estados',
    FAMILIARES: 'https://apiclubsincelejo.prismau.com.co/api/familiares',
    INVITADOS: 'https://apiclubsincelejo.prismau.com.co/api/invitados',
    LOGIN: 'https://apiclubsincelejo.prismau.com.co/api/login',
    PERSONAL: 'https://apiclubsincelejo.prismau.com.co/api/personal',
    USUARIOS: 'https://apiclubsincelejo.prismau.com.co/api/usuario',
    NOTICIAS: 'https://apiclubsincelejo.prismau.com.co/api/noticias',
    CONTRATOS: 'https://apiclubsincelejo.prismau.com.co/api/contratos',
    RESET: 'https://apiclubsincelejo.prismau.com.co/api/reset-password',
    VERIFY_CODE: 'https://apiclubsincelejo.prismau.com.co/api/verify-reset-code',
    CHANGE_PASSWORD: 'https://apiclubsincelejo.prismau.com.co/api/change-password',
    SOLICITUDES: 'https://apiclubsincelejo.prismau.com.co/api/solicitudes',
    DISPONIBILIDADES_ESPACIOS: 'https://apiclubsincelejo.prismau.com.co/api/disponibilidad-espacio',
    RESERVAS: 'https://apiclubsincelejo.prismau.com.co/api/reservas',
    ENCUESTAS: 'https://apiclubsincelejo.prismau.com.co/api/encuestas',
    PREGUNTAS: 'https://apiclubsincelejo.prismau.com.co/api/preguntas',
    RESPUESTAS: 'https://apiclubsincelejo.prismau.com.co/api/respuestas',
    MENUS: 'https://apiclubsincelejo.prismau.com.co/api/menus',
    RUBROS: 'https://apiclubsincelejo.prismau.com.co/api/rubros',
    MENSUALIDADES: 'https://apiclubsincelejo.prismau.com.co/api/mensualidades',
    PREFERENCIA: 'https://apiclubsincelejo.prismau.com.co/api/preferencia',
    PAGOS: 'https://apiclubsincelejo.prismau.com.co/api/pagos',
    CUOTAS_BAILE: 'https://apiclubsincelejo.prismau.com.co/api/cuotas-baile',
}

// export const EndPoints = {
//     ACCESOS: "http://127.0.0.1:8000/api/entradas",
//     ADHERENTES: 'http://127.0.0.1:8000/api/adherentes',
//     ADMINS: 'http://127.0.0.1:8000/api/admin',
//     ASOCIADOS: 'http://127.0.0.1:8000/api/asociados',
//     EMPLEADOS: 'http://127.0.0.1:8000/api/empleados',
//     ESPACIOS: 'http://127.0.0.1:8000/api/espacios',
//     ESTADOS: 'http://127.0.0.1:8000/api/estados',
//     FAMILIARES: 'http://127.0.0.1:8000/api/familiares',
//     INVITADOS: 'http://127.0.0.1:8000/api/invitados',
//     LOGIN: 'http://127.0.0.1:8000/api/login',
//     PERSONAL: 'http://127.0.0.1:8000/api/personal',
//     USUARIOS: 'http://127.0.0.1:8000/api/usuario',
//     NOTICIAS: 'http://127.0.0.1:8000/api/noticias',
//     CONTRATOS: 'http://127.0.0.1:8000/api/contratos',
//     RESET: 'http://127.0.0.1:8000/api/reset-password',
//     VERIFY_CODE: 'http://127.0.0.1:8000/api/verify-reset-code',
//     CHANGE_PASSWORD: 'http://127.0.0.1:8000/api/change-password',
//     SOLICITUDES: 'http://127.0.0.1:8000/api/solicitudes',
//     DISPONIBILIDADES_ESPACIOS: 'http://127.0.0.1:8000/api/disponibilidad-espacio',
//     RESERVAS: 'http://127.0.0.1:8000/api/reservas',
//     ENCUESTAS: 'http://127.0.0.1:8000/api/encuestas',
//     PREGUNTAS: 'http://127.0.0.1:8000/api/preguntas',
//     RESPUESTAS: 'http://127.0.0.1:8000/api/respuestas',
//     MENUS: 'http://127.0.0.1:8000/api/menus',
//     RUBROS: 'http://127.0.0.1:8000/api/rubros',
//     MENSUALIDADES: 'http://127.0.0.1:8000/api/mensualidades',
//     PREFERENCIA: 'http://127.0.0.1:8000/api/preferencia',
//     PAGOS: 'http://127.0.0.1:8000/api/pagos',
//     CUOTAS_BAILE: 'http://127.0.0.1:8000/api/cuotas-baile',
// }