// export const RouteBack = "http://127.0.0.1:8000";
export const RouteBack = "https://www.apiclubsincelejo.prismau.co";

export const PublicRoutes = {
    LOGIN: "/",
    RECUPERAR: "/reset-user",
    VALIDAR: "/validate-code",
    RESET: "/change-password",
};

export const PrivateRoutes = {
    DASHBOARD: "/dashboard",
    BUSCAR_USER: "/busqueda-usuarios",
    ADMINISTRADORES: "/administradores",
    ASOCIADOS: "/asociados",
    ADHERENTES: "/adherentes",
    EMPLEADOS: "/empleados",
    ESPACIOS: "/espacios",
    ROLES: "/roles",
    HOBBIES: "/hobbies",
    FAMILIARES: "/familiares",
    FAMILIARESASOCIADO: "/familiares-asociado",
    FAMILIARESADHERENTE: "/familiares-adherente",
    PERFIL: "/perfil",
    INVITADOS: "/invitados",
    INVITACIONES: "/invitaciones",
    CARGOS: "/cargos",
    ACCESOS: "/accesos",
    ESTADOS: "/estados",
    NOTICIAS: "/noticias",
    PAGE403: "/403",
    CONTRATOS: "/contratos",
    SOLICITUDES: "/solicitudes",
    RESERVAS: "/reservas",
    ENCUESTAS: "/encuestas",
    DISPONIBILIDAD_ESPACIO: "/disponibilidades-espacios",
    PREGUNTAS: "/preguntas",
    RESPUESTAS: "/respuestas",
};

// export const EndPoints = {
//     ACCESOS: "https://www.apiclubsincelejo.prismau.co/api/entradas",
//     ADHERENTES: 'https://www.apiclubsincelejo.prismau.co/api/adherentes',
//     ADMINS: 'https://www.apiclubsincelejo.prismau.co/api/admin',
//     ASOCIADOS: 'https://www.apiclubsincelejo.prismau.co/api/asociados',
//     EMPLEADOS: 'https://www.apiclubsincelejo.prismau.co/api/empleados',
//     ESPACIOS: 'https://www.apiclubsincelejo.prismau.co/api/espacios',
//     ESTADOS: 'https://www.apiclubsincelejo.prismau.co/api/estados',
//     FAMILIARES: 'https://www.apiclubsincelejo.prismau.co/api/familiares',
//     INVITADOS: 'https://www.apiclubsincelejo.prismau.co/api/invitados',
//     LOGIN: 'https://www.apiclubsincelejo.prismau.co/api/login',
//     PERSONAL: 'https://www.apiclubsincelejo.prismau.co/api/personal',
//     USUARIOS: 'https://www.apiclubsincelejo.prismau.co/api/usuario',
//     NOTICIAS: 'https://www.apiclubsincelejo.prismau.co/api/noticias',
//     CONTRATOS: 'https://www.apiclubsincelejo.prismau.co/api/contratos',
//     RESET: 'https://www.apiclubsincelejo.prismau.co/api/reset-password',
//     VERIFY_CODE: 'https://www.apiclubsincelejo.prismau.co/api/verify-reset-code',
//     CHANGE_PASSWORD: 'https://www.apiclubsincelejo.prismau.co/api/change-password',
//     SOLICITUDES: 'https://www.apiclubsincelejo.prismau.co/api/solicitudes',
//     DISPONIBILIDADES_ESPACIOS: 'https://www.apiclubsincelejo.prismau.co/api/disponibilidad-espacio',
//     RESERVAS: 'https://www.apiclubsincelejo.prismau.co/api/reservas',
//     ENCUESTAS: 'https://www.apiclubsincelejo.prismau.co/api/encuestas',
//     PREGUNTAS: 'https://www.apiclubsincelejo.prismau.co/api/preguntas',
//     RESPUESTAS: 'https://www.apiclubsincelejo.prismau.co/api/respuestas',
// }

export const EndPoints = {
    ACCESOS: "http://127.0.0.1:8000/api/entradas",
    ADHERENTES: 'http://127.0.0.1:8000/api/adherentes',
    ADMINS: 'http://127.0.0.1:8000/api/admin',
    ASOCIADOS: 'http://127.0.0.1:8000/api/asociados',
    EMPLEADOS: 'http://127.0.0.1:8000/api/empleados',
    ESPACIOS: 'http://127.0.0.1:8000/api/espacios',
    ESTADOS: 'http://127.0.0.1:8000/api/estados',
    FAMILIARES: 'http://127.0.0.1:8000/api/familiares',
    INVITADOS: 'http://127.0.0.1:8000/api/invitados',
    LOGIN: 'http://127.0.0.1:8000/api/login',
    PERSONAL: 'http://127.0.0.1:8000/api/personal',
    USUARIOS: 'http://127.0.0.1:8000/api/usuario',
    NOTICIAS: 'http://127.0.0.1:8000/api/noticias',
    CONTRATOS: 'http://127.0.0.1:8000/api/contratos',
    RESET: 'http://127.0.0.1:8000/api/reset-password',
    VERIFY_CODE: 'http://127.0.0.1:8000/api/verify-reset-code',
    CHANGE_PASSWORD: 'http://127.0.0.1:8000/api/change-password',
    SOLICITUDES: 'http://127.0.0.1:8000/api/solicitudes',
    DISPONIBILIDADES_ESPACIOS: 'http://127.0.0.1:8000/api/disponibilidad-espacio',
    RESERVAS: 'http://127.0.0.1:8000/api/reservas',
    ENCUESTAS: 'http://127.0.0.1:8000/api/encuestas',
    PREGUNTAS: 'http://127.0.0.1:8000/api/preguntas',
    RESPUESTAS: 'http://127.0.0.1:8000/api/respuestas',
}